-- ============================================================
-- WhatSaaS SaaS Plans Seed Data
-- Run this AFTER migrations to set up your pricing plans.
-- ============================================================
--
-- PRICING STRATEGY:
--   Free     ($0/mo)  — Voor evaluatie / kleine teams
--   Starter  ($29/mo) — Kleine bedrijven, 1 WhatsApp nummer
--   Pro      ($79/mo) — Grotere teams, AI + Flow Builder
--   Enterprise ($199/mo) — Volledige features, onbeperkt
--
-- BEFORE RUNNING:
--   1. Create these products in Stripe Dashboard
--   2. Copy the Stripe Price IDs below
--   3. Set trialDays to 14 for paid plans (STRIPE side)
-- ============================================================

-- Example INSERT (adjust stripePriceId with your actual Stripe Price IDs):
-- INSERT INTO plans (name, description, stripeProductId, stripePriceId, amount, currency, "interval", trialDays, maxUsers, maxContacts, maxInstances, isAiEnabled, isFlowBuilderEnabled, isCampaignsEnabled, isTemplatesEnabled, isVoiceCallsEnabled)
-- VALUES
--   (
--     'free', 'Free plan for evaluation', '', '', 0, 'usd', 'month', 0,
--     1, 100, 1,
--     false, false, false, false, false
--   ),
--   (
--     'starter', 'Starter plan for small teams', '', '', 2900, 'usd', 'month', 14,
--     3, 1000, 1,
--     false, true, false, true, false
--   ),
--   (
--     'pro', 'Pro plan with AI and advanced automation', '', '', 7900, 'usd', 'month', 14,
--     10, 10000, 3,
--     true, true, true, true, false
--   ),
--   (
--     'enterprise', 'Enterprise plan with unlimited usage', '', '', 19900, 'usd', 'month', 14,
--     100, 100000, 10,
--     true, true, true, true, true
--   );

-- ============================================================
-- STRIPE SETUP CHECKLIST:
-- ============================================================
-- 1. Go to https://dashboard.stripe.com/products
-- 2. Create 4 products matching the plans above
-- 3. For each product, create a monthly price and yearly price
-- 4. Copy the Price IDs (price_xxx) into the INSERT above
-- 5. Set up Webhook pointing to: https://yourdomain.com/api/stripe/webhook
-- 6. Enable these webhook events:
--    - checkout.session.completed
--    - customer.subscription.updated
--    - customer.subscription.deleted
--    - invoice.payment_failed
-- ============================================================
